language: objective-c

branches:
  only:
  - master
  
xcode_project: SwipyCell.xcodeproj
xcode_scheme: SwipyCell
osx_image: xcode7.2
xcode_sdk: iphonesimulator9.0

script:
- pod lib lint
- xcodebuild clean build -project SwipyCell.xcodeproj -scheme SwipyCell CODE_SIGNING_REQUIRED=NO
