language: objective-c

xcode_project: SwipyCell.xcodeproj
xcode_scheme: SwipyCell
osx_image: xcode8
xcode_sdk: iphonesimulator10.0

before_install:
  - gem update cocoapods
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script:
- xcodebuild -project SwipyCell.xcodeproj -scheme SwipyCell -sdk iphonesimulator clean build | xcpretty
- pod lib lint
